services:
  vivu-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vivu-backend

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


    ports:
      - "8081:8080"
    env_file:
      - .env.docker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vivudb
      SPRING_REDIS_HOST: redis
      SPRING_BOOT_ADMIN_CLIENT_ENABLED: "false"

    networks:
      - vivu-network
    restart: unless-stopped

    develop:
      watch:
        - path: .
          action: rebuild
          ignore:
            - .git
            - .idea
            - target
            - mvnw.cmd

  postgres:
    image: postgres:16-alpine
    container_name: vivu-postgres

    environment:
      POSTGRES_DB: vivudb
      POSTGRES_USER: vivu
      POSTGRES_PASSWORD: vivu

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - vivu-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: vivu-redis

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - vivu-network
    restart: unless-stopped

networks:
  vivu-network:
    driver: bridge

volumes:
  postgres-data:
